theme: minima

title: Nagwa Khordagui
description: Applied Economist & Data Scientist
url: "https://nkhordagui.github.io"

header_pages:
  - research.md
  - skills.md
  - projects.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
